import { useState, useEffect, useRef } from 'react'
import { api } from '../api/client'
import LogViewer from './LogViewer'
import StageProgress from './StageProgress'

const STAGES = ['Scene Parser', 'Voice Synthesis']

interface AudioResult {
  scene_id: number
  status: string
}

interface TaskEntry {
  scene_id: number
  location: string
}

type StageState = 'idle' | 'running' | 'done' | 'error'

interface Phase2Status {
  status: 'idle' | 'running' | 'completed' | 'error'
  task_graph: TaskEntry[]
  audio_results: AudioResult[]
  error?: string
  stages: Record<string, StageState>
}

interface Props {
  logs: string[]
  onClearLogs: () => void
}

function audioIcon(status: string) {
  if (status === 'done')    return { icon: '✅', cls: 'text-noir-green' }
  if (status === 'skipped') return { icon: '⏭', cls: 'text-noir-muted' }
  if (status === 'error')   return { icon: '❌', cls: 'text-noir-red' }
  return { icon: '⏳', cls: 'text-noir-muted' }
}

export default function Phase2Panel({ logs, onClearLogs }: Props) {
  const [status, setStatus] = useState<Phase2Status>({
    status: 'idle',
    task_graph: [],
    audio_results: [],
    stages: Object.fromEntries(STAGES.map((s) => [s, 'idle' as StageState])),
  })
  const [error, setError] = useState<string | null>(null)
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null)

  const isRunning = status.status === 'running'

  const stopPoll = () => {
    if (pollRef.current) { clearInterval(pollRef.current); pollRef.current = null }
  }

  const startPoll = () => {
    stopPoll()
    pollRef.current = setInterval(async () => {
      try {
        const s = await api.getPhase2Status() as Phase2Status
        setStatus(s)
        if (s.status !== 'running') stopPoll()
      } catch {}
    }, 1000)
  }

  useEffect(() => () => stopPoll(), [])

  const handleRun = async () => {
    try {
      setError(null)
      onClearLogs()
      await api.runPhase2()
      setStatus({
        status: 'running',
        task_graph: [],
        audio_results: [],
        stages: Object.fromEntries(STAGES.map((s) => [s, 'idle' as StageState])),
      })
      startPoll()
    } catch (e) {
      setError((e as Error).message)
    }
  }

  const audioMap = Object.fromEntries(
    status.audio_results.map((r) => [r.scene_id, r.status])
  )

  const statusLabel = {
    idle: 'Ready — run Phase 1 first',
    running: '⏳ Pipeline running…',
    completed: '✅ Phase 2 Complete',
    error: '❌ Error — see log',
  }[status.status]

  return (
    <div className="flex h-full p-5 gap-5 overflow-hidden">
      {/* ── Left column ── */}
      <div className="flex flex-col gap-4 w-[45%] overflow-y-auto pr-1">
        {/* Info banner */}
        <div className="bg-noir-bg2 border border-noir-border rounded p-4">
          <div className="text-xs font-bold text-noir-gold tracking-wider mb-2">PHASE 1 OUTPUTS</div>
          <p className="text-xs text-noir-muted mb-2">
            Phase 2 reads outputs generated by Phase 1 automatically.
          </p>
          {['outputs/scene_manifest.json', 'outputs/character_db.json'].map((f) => (
            <div key={f} className="flex items-center gap-2 py-1">
              <span className="text-noir-muted text-xs">▸</span>
              <span className="text-xs font-mono text-noir-muted">{f}</span>
            </div>
          ))}
        </div>

        {/* Run button */}
        <button
          onClick={handleRun}
          disabled={isRunning}
          className="w-full py-3 bg-noir-gold text-noir-bg font-bold text-sm tracking-widest rounded hover:bg-noir-gold2 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
        >
          {isRunning ? '⏳  RUNNING…' : '▶  RUN PHASE 2 PIPELINE'}
        </button>

        {/* Error */}
        {error && (
          <div className="bg-noir-bg2 border border-noir-red rounded p-3 text-xs text-noir-red">
            ❌ {error}
          </div>
        )}

        <StageProgress stages={STAGES} stageStatus={status.stages} />

        {/* Scene status table */}
        {status.task_graph.length > 0 && (
          <div className="bg-noir-bg2 border border-noir-border rounded p-4">
            <div className="text-xs font-bold text-noir-gold tracking-wider mb-3">SCENE STATUS</div>
            <div className="grid text-xs font-bold text-noir-gold mb-2" style={{ gridTemplateColumns: '3rem 1fr 4rem' }}>
              <span>SCENE</span>
              <span>LOCATION</span>
              <span>AUDIO</span>
            </div>
            <div className="flex flex-col gap-1">
              {status.task_graph.map((task) => {
                const ast = audioMap[task.scene_id] ?? 'pending'
                const { icon, cls } = audioIcon(ast)
                const loc = task.location.length > 24
                  ? task.location.slice(0, 23) + '…'
                  : task.location
                return (
                  <div
                    key={task.scene_id}
                    className="grid bg-noir-bg3 rounded px-2 py-1 text-xs text-noir-muted"
                    style={{ gridTemplateColumns: '3rem 1fr 4rem' }}
                  >
                    <span>{task.scene_id}</span>
                    <span>{loc}</span>
                    <span className={cls}>{icon}</span>
                  </div>
                )
              })}
            </div>
          </div>
        )}

        {/* Output files */}
        {status.status === 'completed' && (
          <div className="bg-noir-bg2 border border-noir-border rounded p-4">
            <div className="text-xs font-bold text-noir-gold tracking-wider mb-2">OUTPUT FILES</div>
            {[
              'outputs/audio/scene_*.wav',
              'outputs/timing_manifest.json',
              'outputs/phase2_manifest.json',
              'outputs/logs/phase2_task_log.json',
            ].map((f) => (
              <div key={f} className="flex items-center gap-2 py-1">
                <span className="text-noir-green text-xs">▸</span>
                <span className="text-noir-green text-xs font-mono">{f}</span>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* ── Right column ── */}
      <div className="flex flex-col gap-4 flex-1 min-h-0">
        {/* Status bar */}
        <div className="bg-noir-bg2 border border-noir-border rounded px-4 py-2">
          <span className="text-xs font-bold text-noir-gold tracking-wider">STATUS&nbsp;&nbsp;</span>
          <span className={`text-xs ${status.status === 'error' ? 'text-noir-red' : status.status === 'completed' ? 'text-noir-green' : 'text-noir-muted'}`}>
            {statusLabel}
          </span>
        </div>
        <LogViewer logs={logs} title="LIVE LOG" />
      </div>
    </div>
  )
}
